"""Full re-run of every backtest scenario + inference with current code.

Regenerates the data/backtest_v2_*.csv and data/inference_*.csv result
files from a single, self-consistent execution — fixing the stale
HRP_PartialCorr rows (the headline CSVs predate bug fix #5, in which
HRP_PartialCorr degenerated byte-identically to IVP).

Scenarios: B (monthly-rebalanced headline, 19 strategies), the cost grid,
Scenario A (static buy-and-hold), threshold C/C', and the post-COVID
regime cut. Inference (Ledoit-Wolf Sharpe-diff, Hansen SPA, stationary
block-bootstrap CIs) is recomputed on the fresh Scenario-B series.

Writes CSVs incrementally so partial progress is usable.
"""
from __future__ import annotations

import pickle
import time
import warnings

import numpy as np
import pandas as pd

import sys
# --- resolve the repo root so this script runs from any cwd / machine ---
import os as _os
from pathlib import Path as _Path
_ROOT = _Path(__file__).resolve().parents[1]
sys.path.insert(0, str(_ROOT))
_os.chdir(_ROOT)

from src.backtest import WalkForwardBacktest, COST_SCENARIOS, summarize_performance
from src.portfolio_maker import (
    HRP, HRPDetoned, HRPPartialCorr, HRPDynamic, HRPTailDep, HRPTailDepShrunk,
    HRPShrunkCov, HRPVolStd, IVP, MVP, ERC, MaxDiv, HERC, NCO,
    CrossSectionalMomentum, RiskManagedMomentum, MomentumHRP,
    HRPPathSig, HRPNodeEmbed, HRPContrastive, HRPTS2Vec,
)
from src.inference import (
    stationary_block_bootstrap, sharpe_diff_ledoit_wolf, hansen_spa_test,
)
from src.universe import load_pit_universe

warnings.filterwarnings("ignore")
ANN = np.sqrt(365)
DATA = str(_ROOT / "data")

# ---------- data ----------
print("Loading data...", flush=True)
pit = load_pit_universe(f"{DATA}/pit_universe.csv")
ex = pd.read_csv(f"{DATA}/binance_usdt_pairs_2018-12-31_2024-01-01_1d.csv", parse_dates=["open_time"])
sp = pd.read_csv(f"{DATA}/binance_pit_supplement_2019-2024_1d.csv", parse_dates=["open_time"])
pl = pd.concat([ex, sp], ignore_index=True).drop_duplicates(subset=["symbol", "open_time"])
pl["close"] = pl["close"].astype(float)
prices = pl.pivot(index="open_time", columns="symbol", values="close").sort_index()
print(f"  prices {prices.shape}", flush=True)

# ---------- strategy roster (19 + HODL) ----------
FACTORIES = {
    "HRP":               lambda r: HRP(r),
    "HRP_Detoned":       lambda r: HRPDetoned(r),
    "HRP_PartialCorr":   lambda r: HRPPartialCorr(r),
    "HRP_Dynamic_94":    lambda r: HRPDynamic(r, lam=0.94),
    "HRP_TailDep":       lambda r: HRPTailDep(r, q=0.05),
    "HRP_TailDepShrunk": lambda r: HRPTailDepShrunk(r, q=0.05),
    "HRP_ShrunkCov":     lambda r: HRPShrunkCov(r),
    "HRP_VolStd":        lambda r: HRPVolStd(r),
    "IVP":               lambda r: IVP(r),
    "MVP":               lambda r: MVP(r),
    "ERC":               lambda r: ERC(r),
    "MaxDiv":            lambda r: MaxDiv(r),
    "CS_MOM_eq21":       lambda r: CrossSectionalMomentum(
        r, formation_period=21, top_percentile=0.3,
        bottom_percentile=0.2, weighting_scheme="equal"),
    "RM_MOM":            lambda r: RiskManagedMomentum(
        r, formation_period=21, vol_lookback=63,
        target_volatility=0.12, top_percentile=0.3),
    "MOM_HRP":           lambda r: MomentumHRP(
        r, formation_period=21, top_percentile=0.4, min_assets=5),
    "HERC":              lambda r: HERC(r),
    "NCO":               lambda r: NCO(r),
    "HRP_PathSig":       lambda r: HRPPathSig(r),
    "HRP_NodeEmbed":     lambda r: HRPNodeEmbed(r),
    "HRP_Contrastive":   lambda r: HRPContrastive(r),
    "HRP_TS2Vec":        lambda r: HRPTS2Vec(r),
}
# strategies that do NOT retrain a neural / random-walk embedding each
# snapshot — safe to re-run at weekly cadence (the embeddings are not).
NON_EMBED = [k for k in FACTORIES if k not in
             ("HRP_PathSig", "HRP_NodeEmbed", "HRP_Contrastive", "HRP_TS2Vec")]


def metrics_row(name, daily, res=None):
    """Headline metric row matching backtest_v2_rebalance_results.csv schema."""
    m = summarize_performance(daily, name=name)
    row = {k: m.get(k) for k in ("total_return", "ann_return", "ann_vol",
                                 "sharpe", "sortino", "max_drawdown",
                                 "calmar", "n_days")}
    row["name"] = name
    row["arith_sharpe_ann"] = float(daily.mean() / daily.std(ddof=1) * ANN) if daily.std(ddof=1) > 0 else 0.0
    if res is not None:
        wh = res["weights_history"]
        th, ch = res["turnover_history"], res["cost_history"]
        row["rebalances"] = float(len(res["snapshot_dates"]))
        row["avg_turnover"] = float(np.mean(np.asarray(th))) if len(th) else 0.0
        row["total_costs"] = float(np.sum(np.asarray(ch))) if len(ch) else 0.0
        if len(wh):
            W = wh.fillna(0.0)
            row["avg_max_weight"] = float(W.max(axis=1).mean())
            row["avg_n_eff"] = float((1.0 / (W ** 2).sum(axis=1)).mean())
    return row


def run_scenario(start, end, rebalance_mode="calendar", cost="conservative_cex",
                 names=None, label=""):
    """Run a set of strategies; return {name: result dict} and {name: daily}."""
    names = names or list(FACTORIES)
    cm = COST_SCENARIOS[cost]
    out, daily = {}, {}
    for i, name in enumerate(names, 1):
        t0 = time.time()
        kw = {}
        if rebalance_mode != "calendar":
            kw["rebalance_mode"] = rebalance_mode
            if rebalance_mode == "threshold_smoothed":
                kw.update(drift_threshold=0.25, smoothing_eta=0.25, min_trade_bps=25.0)
            else:
                kw["drift_threshold"] = 0.05
        bt = WalkForwardBacktest(prices, pit, FACTORIES[name], cost_model=cm, **kw)
        res = bt.run(start, end)
        out[name] = res
        daily[name] = res["daily_returns"]
        d = res["daily_returns"]
        sh = d.mean() / d.std(ddof=1) * ANN if d.std(ddof=1) > 0 else 0.0
        print(f"  [{label} {i}/{len(names)}] {name:18s} Sharpe={sh:+.4f} "
              f"TR={((1+d).prod()-1)*100:+.0f}% [{time.time()-t0:.0f}s]", flush=True)
    return out, daily


# =====================================================================
# Scenario B — headline, 19 strategies, monthly calendar rebalance
# =====================================================================
print("\n=== Scenario B (headline) ===", flush=True)
t0 = time.time()
resB, dailyB = run_scenario("2020-01-01", "2026-05-18", label="B")
# HODL_BTC on the SAME out-of-sample window as the strategies, so the
# table, the CIs and the SPA all use one consistent BTC series.
strat_idx = pd.DataFrame(dailyB).dropna().index
hodl = prices["BTCUSDT"].pct_change().reindex(strat_idx)
dailyB["HODL_BTC"] = hodl

rows = [metrics_row(n, dailyB[n], resB[n]) for n in FACTORIES]
rows.append(metrics_row("HODL_BTC", hodl, None))
cols = ["name", "total_return", "ann_return", "ann_vol", "sharpe", "sortino",
        "max_drawdown", "calmar", "n_days", "arith_sharpe_ann", "rebalances",
        "avg_turnover", "total_costs", "avg_max_weight", "avg_n_eff"]
pd.DataFrame(rows)[cols].to_csv(f"{DATA}/backtest_v2_rebalance_results.csv", index=False)
with open(f"{DATA}/backtest_v2_daily_returns.pkl", "wb") as f:
    pickle.dump(dailyB, f)
print(f"  -> backtest_v2_rebalance_results.csv  [{time.time()-t0:.0f}s]", flush=True)

# =====================================================================
# Inference on Scenario B
# =====================================================================
print("\n=== Inference (Scenario B) ===", flush=True)
rdf = pd.DataFrame(dailyB).dropna()
hrp = rdf["HRP"]
sh = {c: rdf[c].mean() / rdf[c].std(ddof=1) * ANN for c in rdf.columns}

lw_rows, ci_rows = [], []
for c in rdf.columns:
    boot = stationary_block_bootstrap(
        rdf[c].values,
        lambda r: float(np.mean(r) / np.std(r, ddof=1) * ANN) if np.std(r, ddof=1) > 0 else 0.0,
        n_iter=2000, seed=42)
    ci_rows.append({"name": c, "sharpe": sh[c],
                    "ci_lower_95": boot["ci_lower_95"], "ci_upper_95": boot["ci_upper_95"]})
    if c == "HRP":
        continue
    # candidate vs HRP; sharpe_diff_vs_hrp = candidate - HRP (positive = better)
    lw = sharpe_diff_ledoit_wolf(rdf[c].values, hrp.values, n_iter=3000, seed=42)
    lw_rows.append({"name": c, "sharpe_diff_vs_hrp": sh[c] - sh["HRP"],
                    "lw_p_value": lw["p_value"]})
pd.DataFrame(lw_rows).to_csv(f"{DATA}/inference_sharpe_diff.csv", index=False)
pd.DataFrame(ci_rows).to_csv(f"{DATA}/inference_bootstrap_cis.csv", index=False)

cand = rdf.drop(columns=["HRP"])
spa = hansen_spa_test(cand, hrp.values, n_bootstrap=5000, seed=42)
spa.to_csv(f"{DATA}/inference_spa.csv")
print(f"  -> inference_*.csv  (SPA p_consistent={spa['p_consistent'].iloc[0]:.4f})", flush=True)

# =====================================================================
# Cost grid — 5-strategy subset across 4 cost models
# =====================================================================
print("\n=== Cost sensitivity ===", flush=True)
cost_names = ["HRP", "HRP_Detoned", "HRP_TailDep", "HRP_ShrunkCov", "MVP"]
crows = []
for cs in ["zero", "conservative_cex", "optimistic_cex", "stress"]:
    o, d = run_scenario("2020-01-01", "2026-05-18", cost=cs, names=cost_names, label=f"cost:{cs}")
    for n in cost_names:
        dd = d[n]
        crows.append({"strategy": n, "cost_scenario": cs,
                      "sharpe_ann": float(dd.mean() / dd.std(ddof=1) * ANN),
                      "total_return": float((1 + dd).prod() - 1),
                      "avg_turnover": float(np.mean(np.asarray(o[n]["turnover_history"]))),
                      "total_costs": float(np.sum(np.asarray(o[n]["cost_history"])))})
pd.DataFrame(crows).to_csv(f"{DATA}/backtest_v2_cost_sensitivity.csv", index=False)
print("  -> backtest_v2_cost_sensitivity.csv", flush=True)

# =====================================================================
# Threshold C / C'
# =====================================================================
print("\n=== Threshold scenarios ===", flush=True)
thr_names = ["HRP", "HRP_TailDep", "HRP_ShrunkCov", "MVP", "RM_MOM"]
trows = []
for mode, scen in [("calendar", "B_calendar"), ("threshold", "C_threshold_5pct"),
                   ("threshold_smoothed", "Cprime_smoothed_e25_t25")]:
    o, d = run_scenario("2020-01-01", "2026-05-18", rebalance_mode=mode,
                        names=thr_names, label=scen)
    for n in thr_names:
        dd = d[n]
        trows.append({"strategy": n, "scenario": scen,
                      "sharpe_ann": float(dd.mean() / dd.std(ddof=1) * ANN),
                      "total_return": float((1 + dd).prod() - 1),
                      "avg_turnover": float(np.mean(np.asarray(o[n]["turnover_history"]))),
                      "actual_rebalances": int(len(o[n]["snapshot_dates"]))})
pd.DataFrame(trows).to_csv(f"{DATA}/backtest_v2_threshold_results.csv", index=False)
print("  -> backtest_v2_threshold_results.csv", flush=True)

# =====================================================================
# Post-COVID regime cut (2022-01-01 onward)
# =====================================================================
print("\n=== Post-COVID regime ===", flush=True)
t0 = time.time()
resP, dailyP = run_scenario("2022-01-01", "2026-05-18", label="postcovid")
strat_idxP = pd.DataFrame(dailyP).dropna().index
hodlP = prices["BTCUSDT"].pct_change().reindex(strat_idxP)
dailyP["HODL_BTC"] = hodlP
rowsP = [metrics_row(n, dailyP[n], resP[n]) for n in FACTORIES]
rowsP.append(metrics_row("HODL_BTC", hodlP, None))
pd.DataFrame(rowsP)[cols].to_csv(f"{DATA}/backtest_v2_post_covid_results.csv", index=False)

rdfP = pd.DataFrame(dailyP).dropna()
hrpP = rdfP["HRP"]
shP = {c: rdfP[c].mean() / rdfP[c].std(ddof=1) * ANN for c in rdfP.columns}
lwP = []
for c in rdfP.columns:
    if c == "HRP":
        continue
    lw = sharpe_diff_ledoit_wolf(rdfP[c].values, hrpP.values, n_iter=3000, seed=42)
    lwP.append({"name": c, "sharpe_diff_vs_hrp": shP[c] - shP["HRP"],
                "lw_p_value": lw["p_value"]})
pd.DataFrame(lwP).to_csv(f"{DATA}/inference_post_covid_sharpe_diff.csv", index=False)
spaP = hansen_spa_test(rdfP.drop(columns=["HRP"]), hrpP.values, n_bootstrap=5000, seed=42)
spaP.to_csv(f"{DATA}/inference_post_covid_spa.csv")
with open(f"{DATA}/backtest_v2_post_covid_daily_returns.pkl", "wb") as f:
    pickle.dump(dailyP, f)
print(f"  -> post-COVID CSVs  (SPA p_consistent={spaP['p_consistent'].iloc[0]:.4f})  [{time.time()-t0:.0f}s]", flush=True)

# =====================================================================
# Weekly-cadence robustness check (non-embedding strategies)
# =====================================================================
# 76 monthly rebalances give wide bootstrap CIs. A weekly cadence gives
# ~4x the rebalances and tighter inference. The PIT universe is monthly,
# so we carry each month-end's included set forward to the Fridays of
# that month (membership monthly, weights recomputed weekly on a rolling
# 365-day window). Embeddings are excluded (retraining 4 encoders at
# ~330 weekly dates is prohibitive); this checks the risk-based family.
print("\n=== Weekly-cadence check (non-embedding) ===", flush=True)
t0 = time.time()
pit_sorted = pit.sort_values("date")
weekly_dates = pd.date_range("2020-01-01", "2026-05-18", freq="W-FRI")
month_ends = sorted(pd.Timestamp(d) for d in pit["date"].unique())
wk_rows = []
for d in weekly_dates:
    prior = [m for m in month_ends if m <= d]
    if not prior:
        continue
    src = prior[-1]
    inc = pit_sorted[(pit_sorted["date"] == src) & pit_sorted["included"]]
    for _, r in inc.iterrows():
        wk_rows.append({"date": d, "symbol": r["symbol"], "included": True})
pit_weekly = pd.DataFrame(wk_rows)

cm = COST_SCENARIOS["conservative_cex"]
wk_daily = {}
for i, name in enumerate(NON_EMBED, 1):
    res = WalkForwardBacktest(prices, pit_weekly, FACTORIES[name],
                              cost_model=cm).run("2020-01-01", "2026-05-18")
    wk_daily[name] = res["daily_returns"]
wk_idx = pd.DataFrame(wk_daily).dropna().index
wk_daily["HODL_BTC"] = prices["BTCUSDT"].pct_change().reindex(wk_idx)
wk_rdf = pd.DataFrame(wk_daily).dropna()
wk_sh = {c: wk_rdf[c].mean() / wk_rdf[c].std(ddof=1) * ANN for c in wk_rdf.columns}
wk_metrics = []
for c in wk_rdf.columns:
    boot = stationary_block_bootstrap(
        wk_rdf[c].values,
        lambda r: float(np.mean(r) / np.std(r, ddof=1) * ANN) if np.std(r, ddof=1) > 0 else 0.0,
        n_iter=2000, seed=42)
    wk_metrics.append({"strategy": c, "sharpe_ann": wk_sh[c],
                       "total_return": float((1 + wk_rdf[c]).prod() - 1),
                       "ci_lower_95": boot["ci_lower_95"],
                       "ci_upper_95": boot["ci_upper_95"]})
pd.DataFrame(wk_metrics).to_csv(f"{DATA}/backtest_v2_weekly_results.csv", index=False)
wk_spa = hansen_spa_test(wk_rdf.drop(columns=["HRP"]), wk_rdf["HRP"].values,
                         n_bootstrap=5000, seed=42)
wk_spa.to_csv(f"{DATA}/inference_weekly_spa.csv")
with open(f"{DATA}/backtest_v2_weekly_daily_returns.pkl", "wb") as f:
    pickle.dump(wk_daily, f)
print(f"  -> weekly CSVs  ({len(wk_rdf)} days, SPA p_consistent="
      f"{wk_spa['p_consistent'].iloc[0]:.4f})  [{time.time()-t0:.0f}s]", flush=True)

print("\nALL DONE.", flush=True)
